name: E2E Test
on: [pull_request]
env:
  REGION: us-central1

jobs:
  get:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get-files.outputs.result }}
    steps:
    - name: Get changed files
      uses: actions/github-script@v6
      id: get-files
      with:
        script: |
          const resp = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{github.event.pull_request.number}}
          });
          const files = resp.data.map((file) => file.filename);
          return files.filter((filename) => filename.startsWith('src'));

  test:
    name: Run Workflows Test Matrix
    runs-on: ubuntu-latest
    needs: get
    strategy:
      matrix: 
        file: ${{ fromJSON(needs.get.outputs.files) }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - id: Authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/182397877917/locations/global/workloadIdentityPools/gha-pool'
        service_account: 'workload-id@my-project.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Deploy Workflow
      id: test
      run: |
        # Create a Workflow name based on the filename
        NAME=${{ matrix.file }}
        TMP_NAME=${NAME:4}  # remove src/
        TMP_NAME=${TMP_NAME/connectors\//}  # remove connectors/ if present
        WORKFLOW=${TMP_NAME//./-} #-${{ github.run_id }}  # convert . to -

        gcloud workflows deploy $WORKFLOW --source ${{ matrix.file }} --location $REGION
        echo '::set-output name=WORKFLOW::$WORKFLOW'

    - name: Clean up Workflow
      if: ${{ always() }}
      run:
        gcloud workflows delete ${{ steps.test.outputs.WORKFLOW }}" --location $REGION
