name: Lint YAML
on: [pull_request]

jobs:
  get:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-files.outputs.matrix }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - id: get-files
        run: |-
          echo "$(find ./src -name "*.yaml")" > _files
          # Create array from find output
          sed -i 's/ /,/g' _files
          echo "matrix=[$(sed -z 's/\n//g' _files)]" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: [get]
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.get.outputs.matrix) }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install yamllint
        run: |-
          pip3 install --user wheel 
          pip3 install --user yamllint==1.26.3

      - name: Lint YAML files
        working-directory: src
        run: yamllint -f github -c $GITHUB_WORKSPACE/tests/.yamllint ${{ matrix.sample }}
