name: Test Schema
on: [pull_request]

env:
  WORKFLOW: schema/workflows.json

jobs:
  # validate:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3

  #     - name: Set up tooling
  #       run: npm install -g ajv-cli

  #     - name: Validate workflow
  #       run: ajv compile -s ${{ env.WORKFLOW }}

  #     - name: Validate cheatsheet
  #       run: ajv validate -s ${{ env.WORKFLOW }} -d cheatsheet.yaml

  get:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-files.outputs.matrix }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - id: get-files
        run: |-
          echo "$(find $GITHUB_WORKSPACE/src -name "*.yaml")" > _files
          # Create array from find output
          echo "matrix=[$(sed -z 's/\n\//, /g' _files)]" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  smoke-test:
    runs-on: ubuntu-latest
    needs: get
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ needs.get.outputs.matrix }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Set up tooling
        run: npm install -g ajv-cli

      - name: Run Smoke Tests
        run: ajv validate -s ${{ env.WORKFLOW }} -d ${{ matrix.sample }}
